#!/usr/bin/env python3
"""AWG Function Generator — desktop UI.

A dark, minimalist Tkinter UI (portfolio aesthetic) that talks to the Pico
firmware over USB CDC serial using the same plain-text protocol:
    f<Hz>, c<cal>, sine/square/noise/am/fm, snr<dB>, m<Hz>, d<amount>, i

Requires pyserial:  pip install pyserial
"""

import math
import queue
import random
import threading
import tkinter as tk
from tkinter import messagebox

try:
    import serial
    from serial.tools import list_ports
except ImportError:
    _root = tk.Tk()
    _root.withdraw()
    messagebox.showerror(
        "AWG — dependency missing",
        "pyserial is not installed.\n\nInstall it with:\n"
        "    py -3.13 -m pip install pyserial",
    )
    _root.destroy()
    raise SystemExit(1)

# ---------------------------------------------------------------------------
# Device constants (mirror firmware/AWG.c)
# ---------------------------------------------------------------------------
SAMPLE_RATE_HZ = 4034843
DAC_BITS = 8
DAC_FULL = (1 << DAC_BITS) - 1      # 255
DAC_MID = 1 << (DAC_BITS - 1)       # 128
HEADROOM = DAC_MID - 1              # 127  (2^(N-1) - 1)
BAUD = 115200

# ---------------------------------------------------------------------------
# Palette — dark, near-black, cream text, mint accent
# ---------------------------------------------------------------------------
BG          = "#0a0a0a"
BG_DEEP     = "#060606"
PANEL       = "#111111"
PANEL_2     = "#181818"
BORDER      = "#262626"
BORDER_SOFT = "#1b1b1b"
TEXT        = "#f0efe6"
TEXT_2      = "#b9b8b0"
MUTED       = "#8a8983"
FAINT       = "#5e5d59"
ACCENT      = "#b5ecda"
ACCENT_DIM  = "#7fb2a4"
ACCENT_BG   = "#16241f"
ACCENT_DK   = "#0a1f1a"
GRID        = "#1c1c1c"
ERR         = "#d98a80"
WARN        = "#e8a05c"
WARN_DIM    = "#7a4d26"

FONT        = ("Segoe UI", 10)
FONT_BOLD   = ("Segoe UI", 10, "bold")
FONT_SMALL  = ("Segoe UI", 9)
FONT_LABEL  = ("Segoe UI", 8, "bold")
FONT_TITLE  = ("Segoe UI", 22, "bold")
FONT_MONO   = ("Consolas", 9)


def amp_from_snr(snr_db):
    """Return (sine peak amplitude A, noise sigma s) in DAC codes for a given SNR."""
    r = 10.0 ** (snr_db / 20.0)
    s = HEADROOM / (math.sqrt(2.0) * r + 4.0)
    a = math.sqrt(2.0) * r * s
    return a, s


def clamp(v, lo, hi):
    return max(lo, min(hi, v))


def fmt_freq(v):
    if v >= 1e6:
        return f"{v / 1e6:.2f}M"
    if v >= 1e3:
        return f"{v / 1e3:.2f}k"
    return f"{v:.0f}"


HELP_TEXT = {
    "sine": (
        "Pure sine from a 256-entry phase-accumulator (DDS) table feeding the 8-bit "
        "R-2R DAC (GPIO 0-7) at 4.03 MS/s. Clean output to ~1 MHz through the "
        "5th-order Butterworth reconstruction filter (~1.5 MHz corner). "
        "The calibration factor tunes the effective sample rate to trim frequency error."
    ),
    "square": (
        "Square wave generated by a PIO state machine on GPIO 9 and buffered by a "
        "TC4427 driver. The ADG1419 switch routes the square path to the BNC, "
        "bypassing the DAC and filter, so edges stay fast."
    ),
    "noise": (
        "A sine summed with pseudorandom Gaussian noise at a user-set SNR.\n"
        "SNR = 20·log10(V_signal_rms / V_noise_rms), measured over the full output "
        "bandwidth (DC to the ~1.5 MHz filter corner).\n"
        "Noise: xorshift32 LFSR → Irwin-Hall(12), crest factor ≈ 6.\n"
        "Amplitude budget: A/√2 = s·10^(SNR/20) with A + 4s = 127 — the sine is scaled "
        "down as SNR drops, and the summed sample is clamped to 0..255.\n"
        "SNR range: 0–60 dB."
    ),
    "am": (
        "Amplitude modulation: the carrier sine (frequency f) has its amplitude varied "
        "by a sine at the modulation frequency. Depth (0–100%) controls how much.\n"
        "Output = carrier · (1 + depth · sin(2π f_m t)).\n"
        "The carrier is scaled to 1/(1+depth) so the envelope peaks always land on "
        "full scale and never clip — 0% depth is a full-scale carrier, 100% depth "
        "halves the carrier so the 2× envelope still fits within the DAC range."
    ),
    "fm": (
        "Frequency modulation: the carrier sine's instantaneous frequency is deviated "
        "by a sine at the modulation frequency.\n"
        "Output = sin(2π f_c t + β·sin(2π f_m t)), β = deviation / f_m.\n"
        "Deviation is in Hz."
    ),
}


class PillButton(tk.Canvas):
    """A rounded, flat button drawn on a Canvas (pill shape)."""

    def __init__(self, master, text, command, width=116, height=38,
                 kind="ghost", selectable=False):
        super().__init__(master, width=width, height=height, bg=BG,
                         highlightthickness=0, bd=0, cursor="hand2")
        self.text = text
        self.command = command
        self.kind = kind
        self.selectable = selectable
        self.selected = False
        self._hover = False
        self._pw = width
        self._ph = height
        self.bind("<Enter>", lambda e: self._set_hover(True))
        self.bind("<Leave>", lambda e: self._set_hover(False))
        self.bind("<Button-1>", self._on_click)
        self._draw()

    def _set_hover(self, on):
        self._hover = on
        self._draw()

    def set_selected(self, selected):
        self.selected = selected
        self._draw()

    def _on_click(self, _event=None):
        if self.command:
            self.command()

    def _draw(self):
        self.delete("all")
        w, h = self._pw, self._ph
        r = h / 2
        fill, outline, fg = BG, BORDER, TEXT_2
        if self.kind == "accent":
            fill = "#c9f6e9" if self._hover else ACCENT
            outline = ACCENT
            fg = ACCENT_DK
        elif self.selectable and self.selected:
            fill = ACCENT_BG
            outline = ACCENT_DIM
            fg = ACCENT
        elif self._hover:
            outline = "#4b4b45"
            fg = TEXT
        self._round_rect(1, 1, w - 1, h - 1, r, fill=fill, outline=outline, width=1)
        self.create_text(w / 2, h / 2, text=self.text, fill=fg, font=FONT_BOLD)

    def _round_rect(self, x1, y1, x2, y2, r, **kw):
        pts = [x1 + r, y1, x2 - r, y1, x2, y1, x2, y1 + r,
               x2, y2 - r, x2, y2, x2 - r, y2, x1 + r, y2,
               x1, y2, x1, y2 - r, x1, y1 + r, x1, y1]
        return self.create_polygon(pts, smooth=True, **kw)


class Dial(tk.Canvas):
    """A rotary gauge (Ookla-speedtest style): a 180° semicircular arc over a large
    centred value, with tick marks and no needle — the accent arc sweeps clockwise
    from the left to show the value. Scroll to turn, click the value to type.
    """

    def __init__(self, master, label, min_val, max_val, value, fmt=None,
                 to_raw=None, parse=None, log=False, step=0.02, on_change=None,
                 warn=None, diameter=120, enabled=True):
        super().__init__(master, width=diameter, height=diameter + 26, bg=PANEL,
                         highlightthickness=0, bd=0)
        self._label = label
        self._min = min_val
        self._max = max_val
        self._log = log
        self._step = step
        self._value = value
        self._fmt = fmt or (lambda v: f"{v:g}")
        self._to_raw = to_raw or (lambda v: f"{v:g}")
        self._parse = parse or (lambda t: float(t))
        self._on_change = on_change
        self._warn = warn
        self._enabled = enabled
        self._editing = False
        self._entry = None
        self._win = None
        self._d = diameter

        self.bind("<Enter>", self._on_enter)
        self.bind("<MouseWheel>", self._on_wheel)
        self.bind("<Button-4>", self._on_wheel)
        self.bind("<Button-5>", self._on_wheel)
        self.bind("<Button-1>", self._on_click)
        self._draw()

    def reconfig(self, label=None, min_val=None, max_val=None, value=None,
                 fmt=None, to_raw=None, parse=None, log=None, step=None):
        if label is not None:
            self._label = label
        if min_val is not None:
            self._min = min_val
        if max_val is not None:
            self._max = max_val
        if fmt is not None:
            self._fmt = fmt
        if to_raw is not None:
            self._to_raw = to_raw
        if parse is not None:
            self._parse = parse
        if log is not None:
            self._log = log
        if step is not None:
            self._step = step
        if value is not None:
            self._value = clamp(value, self._min, self._max)
        self._draw()

    # ----- mapping -----
    def _t(self, v):
        if self._log:
            return (math.log10(v) - math.log10(self._min)) / (
                math.log10(self._max) - math.log10(self._min))
        return (v - self._min) / (self._max - self._min)

    def _v(self, t):
        t = clamp(t, 0.0, 1.0)
        if self._log:
            return self._min * (self._max / self._min) ** t
        return self._min + t * (self._max - self._min)

    def set_enabled(self, enabled):
        self._enabled = enabled
        self.configure(cursor="hand2" if enabled else "arrow")
        self._draw()

    def get_value(self):
        return self._value

    def set_value(self, value):
        self._value = clamp(value, self._min, self._max)
        self._draw()

    # ----- events -----
    def _on_enter(self, _e):
        if self._enabled:
            self.focus_set()

    def _on_wheel(self, e):
        if not self._enabled or self._editing:
            return
        delta = getattr(e, "delta", 0)
        num = getattr(e, "num", 0)
        if num == 4 or delta > 0:
            d = +1
        elif num == 5 or delta < 0:
            d = -1
        else:
            return
        step = self._step
        if getattr(e, "state", 0) & 0x0001:  # Shift = fine
            step /= 10.0
        self._value = self._v(self._t(self._value) + d * step)
        self._draw()
        if self._on_change:
            self._on_change(self._value)

    def _on_click(self, _e):
        if not self._enabled or self._editing:
            return
        self._editing = True
        self._entry = tk.Entry(self, bg=PANEL_2, fg=TEXT, insertbackground=ACCENT,
                               relief="flat", justify="center", font=FONT_BOLD,
                               highlightthickness=1, highlightbackground=ACCENT_DIM,
                               highlightcolor=ACCENT, width=10)
        self._entry.insert(0, self._to_raw(self._value))
        self._entry.select_range(0, "end")
        self._win = self.create_window(self._d / 2, self._d / 2 + 6, window=self._entry)
        self._entry.focus_set()
        self._entry.bind("<Return>", self._commit)
        self._entry.bind("<Escape>", self._cancel)
        self._entry.bind("<FocusOut>", self._commit)

    def _commit(self, _e=None):
        if not self._editing:
            return
        try:
            v = self._parse(self._entry.get())
        except (ValueError, TypeError):
            self._cancel()
            return
        self._finish_edit()
        self.set_value(v)
        if self._on_change:
            self._on_change(self._value)

    def _cancel(self, _e=None):
        if self._editing:
            self._finish_edit()
            self._draw()

    def _finish_edit(self):
        self._editing = False
        if self._win is not None:
            self.delete(self._win)
            self._win = None
        if self._entry is not None:
            self._entry.destroy()
            self._entry = None

    # ----- draw -----
    def _arc(self, bbox, f0, f1, color, width=5):
        self.create_arc(bbox, start=180 * (1.0 - f0), extent=-180 * (f1 - f0),
                        style="arc", outline=color, width=width)

    def _draw(self):
        self.delete("all")
        d = self._d
        cx = d / 2
        cy = d / 2
        r = d / 2 - 6
        bbox = (cx - r, cy - r, cx + r, cy + r)
        t = self._t(self._value)
        accent = ACCENT if self._enabled else FAINT
        track = BORDER if self._enabled else "#1e1e1e"
        warn_fill = WARN if self._enabled else FAINT
        warn_dim = WARN_DIM if self._enabled else track
        warn_t = self._t(self._warn) if self._warn is not None else None

        # semicircular track over the top, min at left (180°) -> max at right (0°)
        self._arc(bbox, 0.0, 1.0, track)

        # static warning band from the threshold to max (signal-quality loss zone)
        if warn_t is not None and warn_t < 1.0:
            self._arc(bbox, warn_t, 1.0, warn_dim)

        # filled arc sweeps clockwise from the left over the top
        if t > 0.001:
            if warn_t is not None and t > warn_t:
                self._arc(bbox, 0.0, warn_t, accent)
                self._arc(bbox, warn_t, t, warn_fill)
            else:
                self._arc(bbox, 0.0, t, accent)

        # tick marks just outside the arc
        n_ticks = 10
        for i in range(n_ticks + 1):
            a = math.radians(180 - 180 * i / n_ticks)
            cos_a, sin_a = math.cos(a), math.sin(a)
            self.create_line(cx + r * cos_a, cy - r * sin_a,
                             cx + (r + 5) * cos_a, cy - (r + 5) * sin_a,
                             fill=FAINT, width=1)

        # large centred value
        fg = TEXT if self._enabled else FAINT
        self.create_text(cx, cy + 6, text=self._fmt(self._value), fill=fg,
                         font=("Segoe UI", 17, "bold"))

        # label below
        self.create_text(cx, d + 12, text=self._label,
                         fill=MUTED if self._enabled else FAINT,
                         font=("Segoe UI", 8, "bold"))


class AwgApp:
    def __init__(self, root):
        self.root = root
        self.ser = None
        self.rx_queue = queue.Queue()
        self.stop_event = threading.Event()
        self.reader_thread = None

        self.mode = "sine"
        self.freq = 1000.0
        self.cal = 1.0
        self.snr = 20.0
        self.mod_freq = 1000.0
        self.mod_amount = 50.0
        self._preview_t = 0.0
        self.port_var = tk.StringVar(value="")

        root.title("AWG — Function Generator")
        root.geometry("900x900")
        root.minsize(760, 820)
        root.configure(bg=BG)

        self._build_ui()
        self._refresh_ports()
        self._set_mode("sine", send=False)
        self.draw_preview()
        self.root.after(50, self._poll_rx)
        self.root.after(50, self._animate)

    # ------------------------------------------------------------------ UI
    def _card(self, parent, padx=28, pady=(0, 14)):
        f = tk.Frame(parent, bg=PANEL, highlightthickness=1,
                     highlightbackground=BORDER_SOFT)
        f.pack(fill="x", padx=padx, pady=pady)
        return f

    def _section_label(self, parent, text):
        tk.Label(parent, text="  ".join(text), bg=PANEL, fg=MUTED,
                 font=FONT_LABEL, anchor="w").pack(fill="x", padx=18, pady=(14, 2))

    def _build_ui(self):
        # Header
        header = tk.Frame(self.root, bg=BG)
        header.pack(fill="x", padx=28, pady=(24, 4))
        tk.Label(header, text="AWG", bg=BG, fg=TEXT, font=FONT_TITLE).pack(side="left")
        tk.Label(header, text="Function Generator", bg=BG, fg=MUTED,
                 font=("Segoe UI", 11)).pack(side="left", padx=(12, 0), pady=(9, 0))
        self.status_lbl = tk.Label(header, text="●  Disconnected", bg=BG,
                                   fg=FAINT, font=FONT_SMALL)
        self.status_lbl.pack(side="right", pady=(10, 0))

        # Connection
        conn = self._card(self.root, pady=(4, 14))
        self._section_label(conn, "CONNECTION")
        row = tk.Frame(conn, bg=PANEL)
        row.pack(fill="x", padx=18, pady=(4, 14))
        self.port_menu = tk.Menu(conn, tearoff=0, bg=PANEL_2, fg=TEXT,
                                 activebackground=ACCENT_BG, activeforeground=ACCENT,
                                 bd=0, font=FONT)
        self.port_btn = tk.Menubutton(row, textvariable=self.port_var, relief="flat",
                                      bg=PANEL_2, fg=TEXT, activebackground=PANEL_2,
                                      activeforeground=ACCENT, highlightthickness=1,
                                      highlightbackground=BORDER, padx=12, pady=7,
                                      anchor="w", cursor="hand2", menu=self.port_menu,
                                      font=FONT)
        self.port_btn.pack(side="left", fill="x", expand=True)
        PillButton(row, "Refresh", self._refresh_ports, width=76, height=30).pack(
            side="left", padx=(10, 0))
        self.connect_btn = PillButton(row, "Connect", self._toggle_connect,
                                      kind="accent", width=96, height=30)
        self.connect_btn.pack(side="left", padx=(10, 0))
        self.notice_lbl = tk.Label(conn, text="", bg=PANEL, fg=ERR, font=FONT_SMALL,
                                   anchor="w")
        self.notice_lbl.pack(fill="x", padx=18, pady=(0, 12))

        # Mode
        mode_card = self._card(self.root)
        self._section_label(mode_card, "MODE")
        mrow = tk.Frame(mode_card, bg=PANEL)
        mrow.pack(fill="x", padx=18, pady=(4, 16))
        self.mode_btns = {}
        for i, (val, label) in enumerate([("sine", "SINE"), ("square", "SQUARE"),
                                          ("noise", "NOISE"), ("am", "AM"),
                                          ("fm", "FM")]):
            b = PillButton(mrow, label, lambda m=val: self._set_mode(m),
                           width=84, height=36, selectable=True)
            b.pack(side="left", padx=(0 if i == 0 else 8, 0))
            self.mode_btns[val] = b

        # Preview
        preview = self._card(self.root)
        self._section_label(preview, "PREVIEW")
        self.canvas = tk.Canvas(preview, height=210, bg=BG_DEEP, highlightthickness=0)
        self.canvas.pack(fill="both", expand=True, padx=18, pady=(2, 16))

        # Parameters (dials)
        params = self._card(self.root)
        self._section_label(params, "PARAMETERS")
        prows = tk.Frame(params, bg=PANEL)
        prows.pack(fill="x", padx=14, pady=(4, 18))
        for i in range(5):
            prows.columnconfigure(i, weight=1)

        self.freq_dial = Dial(prows, "FREQUENCY", 1.0, 2000000.0, self.freq,
                              fmt=fmt_freq, to_raw=lambda v: str(int(round(v))),
                              parse=lambda t: round(float(t)), log=True, step=0.003,
                              warn=900000.0, on_change=self._set_freq, diameter=124)
        self.freq_dial.grid(row=0, column=0)

        self.cal_dial = Dial(prows, "CALIBRATION", 0.5, 1.5, self.cal,
                             fmt=lambda v: f"{v:.4f}", to_raw=lambda v: f"{v:.4f}",
                             parse=lambda t: float(t), step=0.006,
                             on_change=self._set_cal, diameter=124)
        self.cal_dial.grid(row=0, column=1)

        self.snr_dial = Dial(prows, "SNR  (dB)", 0.0, 60.0, self.snr,
                             fmt=lambda v: f"{v:.1f}", to_raw=lambda v: f"{v:.1f}",
                             parse=lambda t: float(t), step=0.02,
                             on_change=self._set_snr, diameter=124)
        self.snr_dial.grid(row=0, column=2)

        self.mod_freq_dial = Dial(prows, "MOD FREQ", 1.0, 1000000.0, self.mod_freq,
                                  fmt=fmt_freq, to_raw=lambda v: str(int(round(v))),
                                  parse=lambda t: round(float(t)), log=True, step=0.004,
                                  on_change=self._set_mod_freq, diameter=124)
        self.mod_freq_dial.grid(row=0, column=3)

        self.mod_amount_dial = Dial(prows, "DEPTH (%)", 0.0, 100.0, self.mod_amount,
                                    fmt=lambda v: f"{v:.0f}%", to_raw=lambda v: f"{v:.1f}",
                                    parse=lambda t: float(t), step=0.01,
                                    on_change=self._set_mod_amount, diameter=124)
        self.mod_amount_dial.grid(row=0, column=4)

        # About
        about = self._card(self.root)
        self._section_label(about, "ABOUT THIS MODE")
        self.help_lbl = tk.Label(about, text="", bg=PANEL, fg=TEXT_2, font=FONT_SMALL,
                                 justify="left", anchor="nw", wraplength=820)
        self.help_lbl.pack(fill="x", padx=18, pady=(2, 16))

        # Device log
        dev = self._card(self.root)
        self._section_label(dev, "DEVICE")
        self.log = tk.Text(dev, height=5, bg=BG_DEEP, fg=MUTED, font=FONT_MONO,
                           relief="flat", highlightthickness=0, wrap="word",
                           state="disabled", padx=10, pady=8)
        self.log.pack(fill="both", expand=False, padx=18, pady=(2, 16))

    # --------------------------------------------------------------- Serial
    def _refresh_ports(self):
        ports = [p.device for p in list_ports.comports()]
        self.port_menu.delete(0, "end")
        if not ports:
            self.port_var.set("")
            self.port_menu.add_command(label="No ports", state="disabled")
            return
        best = None
        for p in list_ports.comports():
            blob = " ".join(filter(None, [p.device, p.description or "", p.hwid or ""])).lower()
            if "pico" in blob or "2e8a" in blob or "usb serial" in blob:
                best = p.device
                break
        chosen = best or ports[0]
        self.port_var.set(chosen)
        for p in ports:
            self.port_menu.add_command(label=p, command=lambda v=p: self.port_var.set(v))

    def _toggle_connect(self):
        if self.ser is not None:
            self._disconnect()
            return
        port = self.port_var.get()
        if not port:
            self._notice("No serial port selected.")
            return
        try:
            self.ser = serial.Serial(port, BAUD, timeout=0.1)
        except serial.SerialException:
            self._notice(f"Could not open {port}.")
            return
        self.stop_event.clear()
        self.reader_thread = threading.Thread(target=self._reader_loop, daemon=True)
        self.reader_thread.start()
        self.connect_btn.text = "Disconnect"
        self.connect_btn._draw()
        self.status_lbl.config(text=f"●  Connected  ·  {port}", fg=ACCENT)
        self._notice("")
        self._log(f"Connected to {port}")
        self._send("i")

    def _disconnect(self):
        self.stop_event.set()
        if self.ser is not None:
            try:
                self.ser.close()
            except serial.SerialException:
                pass
            self.ser = None
        self.connect_btn.text = "Connect"
        self.connect_btn._draw()
        self.status_lbl.config(text="●  Disconnected", fg=FAINT)

    def _reader_loop(self):
        buf = ""
        while not self.stop_event.is_set():
            try:
                chunk = self.ser.read(self.ser.in_waiting or 1)
            except serial.SerialException:
                break
            if chunk:
                buf += chunk.decode("utf-8", errors="replace")
                while "\n" in buf:
                    line, buf = buf.split("\n", 1)
                    self.rx_queue.put(line.rstrip("\r") + "\n")
        if buf:
            self.rx_queue.put(buf)

    def _poll_rx(self):
        try:
            while True:
                data = self.rx_queue.get_nowait()
                self._log(data)
        except queue.Empty:
            pass
        self.root.after(50, self._poll_rx)

    def _send(self, cmd):
        if self.ser is None:
            return
        try:
            self.ser.write((cmd + "\n").encode("utf-8"))
        except serial.SerialException:
            self._disconnect()

    def _log(self, text):
        self.log.config(state="normal")
        for line in text.splitlines():
            self.log.insert("end", line + "\n")
        if int(self.log.index("end-1c").split(".")[0]) > 500:
            self.log.delete("1.0", "200.0")
        self.log.see("end")
        self.log.config(state="disabled")

    def _notice(self, text):
        self.notice_lbl.config(text=text)

    # -------------------------------------------------------------- Actions
    def _set_mode(self, mode, send=True):
        self.mode = mode
        for val, b in self.mode_btns.items():
            b.set_selected(val == mode)
        if send:
            self._send(mode)
        self._notice("")
        self._update_dials_for_mode()
        self._update_help()
        self.draw_preview()

    def _update_dials_for_mode(self):
        m = self.mode
        self.cal_dial.set_enabled(m != "square")
        self.snr_dial.set_enabled(m == "noise")
        self.mod_freq_dial.set_enabled(m in ("am", "fm"))
        self.mod_amount_dial.set_enabled(m in ("am", "fm"))
        if m == "am":
            self.mod_amount_dial.reconfig(
                label="DEPTH (%)", min_val=0.0, max_val=100.0, value=self.mod_amount,
                log=False, fmt=lambda v: f"{v:.0f}%", to_raw=lambda v: f"{v:.1f}",
                parse=float, step=0.01)
        elif m == "fm":
            self.mod_amount_dial.reconfig(
                label="DEVIATION (Hz)", min_val=1.0, max_val=100000.0, value=self.mod_amount,
                log=True, fmt=fmt_freq, to_raw=lambda v: f"{v:.1f}",
                parse=float, step=0.004)

    def _set_freq(self, v):
        self.freq = v
        self._send(f"f{int(round(v))}")
        self.draw_preview()

    def _set_cal(self, v):
        self.cal = v
        self._send(f"c{v:g}")

    def _set_snr(self, v):
        self.snr = v
        self._send(f"snr{v:g}")
        self.draw_preview()

    def _set_mod_freq(self, v):
        self.mod_freq = v
        self._send(f"m{int(round(v))}")

    def _set_mod_amount(self, v):
        self.mod_amount = v
        self._send(f"d{v:g}")
        self.draw_preview()

    # -------------------------------------------------------------- Preview
    def draw_preview(self):
        c = self.canvas
        c.delete("all")
        c.update_idletasks()
        w = c.winfo_width() or 560
        h = c.winfo_height() or 210
        pad_x, pad_y = 12, 14

        def y(code):
            return pad_y + (1.0 - code / DAC_FULL) * (h - 2 * pad_y)

        N = 512
        t = self._preview_t

        def x_of(i):
            return pad_x + (i / N) * (w - 2 * pad_x)

        mode = self.mode

        if mode == "square":
            pts = []
            for i in range(N + 1):
                ang = (i / N) * 4 * math.pi
                code = DAC_FULL if math.sin(ang) >= 0 else 0
                pts.append((x_of(i), y(code)))
            self._polyline(pts, ACCENT, 2)
            title = "square"
        elif mode == "noise":
            a, s = amp_from_snr(self.snr)
            pts_sine, pts_sum = [], []
            for i in range(N + 1):
                ang = (i / N) * 4 * math.pi
                sine_code = DAC_MID + a * math.sin(ang)
                pts_sine.append((x_of(i), y(sine_code)))
                pts_sum.append((x_of(i), y(clamp(sine_code + random.gauss(0.0, s), 0, DAC_FULL))))
            self._polyline(pts_sine, TEXT_2, 1, dash=(2, 2))
            self._polyline(pts_sum, ACCENT, 2)
            title = f"sine + noise  ·  SNR {self.snr:.1f} dB"
        elif mode == "am":
            depth = clamp(self.mod_amount / 100.0, 0.0, 1.0)
            amp = 127.0 / (1.0 + depth)
            pts = []
            for i in range(N + 1):
                x = i / N
                carrier = x * 20 * 2 * math.pi
                modph = x * 2 * 2 * math.pi + t
                code = clamp(DAC_MID + amp * (1.0 + depth * math.sin(modph)) * math.sin(carrier), 0, DAC_FULL)
                pts.append((x_of(i), y(code)))
            self._polyline(pts, ACCENT, 2)
            title = f"AM  ·  depth {self.mod_amount:.0f}%"
        elif mode == "fm":
            beta = clamp(self.mod_amount / 1000.0, 0.0, 12.0)
            pts = []
            for i in range(N + 1):
                x = i / N
                carrier = x * 20 * 2 * math.pi
                modph = x * 2 * 2 * math.pi + t
                code = clamp(DAC_MID + 127.0 * math.sin(carrier + beta * math.sin(modph)), 0, DAC_FULL)
                pts.append((x_of(i), y(code)))
            self._polyline(pts, ACCENT, 2)
            title = f"FM  ·  dev {self.mod_amount:g} Hz"
        else:
            pts = []
            for i in range(N + 1):
                ang = (i / N) * 4 * math.pi
                pts.append((x_of(i), y(DAC_MID + 127.5 * math.sin(ang))))
            self._polyline(pts, ACCENT, 2)
            title = "sine"

        c.create_text(14, 14, text=title, anchor="nw", fill=MUTED, font=FONT_MONO)
        c.create_text(w - 14, 14, text=fmt_freq(self.freq) + " Hz", anchor="ne",
                      fill=FAINT, font=FONT_MONO)

    def _polyline(self, pts, color, width=2, dash=None):
        self.canvas.create_line(*[v for p in pts for v in p], fill=color,
                                width=width, dash=dash)

    def _animate(self):
        if self.mode in ("am", "fm", "noise"):
            self._preview_t += 0.12
            self.draw_preview()
        self.root.after(50, self._animate)

    def _update_help(self):
        self.help_lbl.config(text=HELP_TEXT[self.mode])

    def on_close(self):
        self._disconnect()
        self.root.destroy()


def main():
    root = tk.Tk()
    app = AwgApp(root)
    root.protocol("WM_DELETE_WINDOW", app.on_close)
    root.mainloop()


if __name__ == "__main__":
    try:
        main()
    except Exception:
        import traceback
        messagebox.showerror("AWG — unexpected error", traceback.format_exc())
        raise
